=== YeFungo/EQIML/EQIML/EarthQuake XML및DTD/EarthQuake.DTD
<?xml version="1.0" encoding="euc-kr"?>
<!--엘리먼트 선언-->
<!ELEMENT EarthQuakes (EarthQuake+, EarthQuake_Information+)>
<!ELEMENT EarthQuake (EarthQuake_Force, EarthQuake_location, EarthQuake_location_X, EarthQuake_location_Y, EarthQuake_time)>
<!ELEMENT EarthQuake_Force (#PCDATA)>
<!ELEMENT EarthQuake_location (#PCDATA)>
<!ELEMENT EarthQuake_location_X (#PCDATA)>
<!ELEMENT EarthQuake_location_Y (#PCDATA)>
<!ELEMENT EarthQuake_time (#PCDATA)>
<!ELEMENT EarthQuake_Information (Force+, Content+)>
<!ELEMENT Force (#PCDATA)>
<!ELEMENT Content (#PCDATA)>




<!--속성 선언-->
<!ATTLIST EarthQuake idx ID #REQUIRED>
<!ATTLIST EarthQuake_location_X unit CDATA "위도">
<!ATTLIST EarthQuake_location_Y unit CDATA "경도">
<!ATTLIST EarthQuake_time unit CDATA "분">
<!ATTLIST EarthQuake_Information idx ID #REQUIRED>

=== YeFungo/EQIML/EQIML/EarthQuake XML및DTD/EarthQuake_information.xml
<?xml version="1.0" encoding="euc-kr"?>
<!DOCTYPE EarthQuakes SYSTEM "EarthQuake.dtd">
  <EarthQuakes>

    <EarthQuake idx="E1">
      <EarthQuake_Force>2.4</EarthQuake_Force>
      <EarthQuake_location>제주 서귀포시 동쪽 58km 해역</EarthQuake_location>
      <EarthQuake_location_X unit="X">33.35</EarthQuake_location_X>
      <EarthQuake_location_Y unit="Y">127.17</EarthQuake_location_Y>
      <EarthQuake_time unit="min">2019.05.13.23:50:38</EarthQuake_time>
    </EarthQuake>
    <EarthQuake idx="E2">
      <EarthQuake_Force>2.0</EarthQuake_Force>
      <EarthQuake_location>경북 영덕군 동북동쪽 29km 해역</EarthQuake_location>
      <EarthQuake_location_X unit="X">36.56</EarthQuake_location_X>
      <EarthQuake_location_Y unit="Y">129.64</EarthQuake_location_Y>
      <EarthQuake_time unit="min">2019.05.10.16:05:58</EarthQuake_time>
    </EarthQuake>
    <EarthQuake idx="E3">
      <EarthQuake_Force>2.1</EarthQuake_Force>
      <EarthQuake_location>경북 영덕군 북동쪽 22km 해역</EarthQuake_location>
      <EarthQuake_location_X unit="X">36.55</EarthQuake_location_X>
      <EarthQuake_location_Y unit="Y">129.54</EarthQuake_location_Y>
      <EarthQuake_time unit="min">2019.05.05.16:57:04</EarthQuake_time>
    </EarthQuake>
    <EarthQuake idx="E4">
      <EarthQuake_Force>2.4</EarthQuake_Force>
      <EarthQuake_location>인천 옹진군 백령도 남쪽 60km 해역</EarthQuake_location>
      <EarthQuake_location_X unit="X">37.42</EarthQuake_location_X>
      <EarthQuake_location_Y unit="Y">124.56</EarthQuake_location_Y>
      <EarthQuake_time unit="min">2019.05.04.05:43:15</EarthQuake_time>
    </EarthQuake>
    <EarthQuake idx="E5">
      <EarthQuake_Force>2.5</EarthQuake_Force>
      <EarthQuake_location>제주 제주시 북서쪽 52km 해역</EarthQuake_location>
      <EarthQuake_location_X unit="X">33.79</EarthQuake_location_X>
      <EarthQuake_location_Y unit="Y">126.09</EarthQuake_location_Y>
      <EarthQuake_time unit="min">2019.04.27.01:10:06</EarthQuake_time>
    </EarthQuake>



    <EarthQuake_Information idx="I1">
      <Force>0 ~ 2.9</Force>
      <Content>지진계에 의해서만 탐지가 가능하며 대부분의 사람이 진동을 느끼지 못함.</Content>
    </EarthQuake_Information>
    <EarthQuake_Information idx="I2">
      <Force>3 ~ 3.9</Force>
      <Content>인간은 자주 느끼지만 피해는 입히지 않음</Content>
    </EarthQuake_Information>
    <EarthQuake_Information idx="I3">
      <Force>4 ~ 4.9</Force>
      <Content>방 안의 물건들이 흔들리는 것을 뚜렷이 관찰할 수 있지만 심각한 피해는 입히지 않음</Content>
    </EarthQuake_Information>
    <EarthQuake_Information idx="I4">
      <Force>5 ~ 5.9</Force>
      <Content>좁은 면적에 걸쳐 부실하게 지어진 건물에 심한 손상</Content>
    </EarthQuake_Information>
    <EarthQuake_Information idx="I5">
      <Force>6 ~ 6.9</Force>
      <Content>최대 160km에 걸쳐 건물들을 파괴하며, 1년에 약 120건 발생</Content>
    </EarthQuake_Information>
    <EarthQuake_Information idx="I6">
      <Force>7 ~ 7.9</Force>
      <Content>넓은 지역에 걸쳐 심한 피해를 입히며, 1년에 약 18건 정도 발생</Content>
    </EarthQuake_Information>
    <EarthQuake_Information idx="I7">
      <Force>8 ~ 8.9</Force>
      <Content>수백km 지역에 걸쳐 심한 피해를 입히며, 1년에 1건 정도 발생</Content>
    </EarthQuake_Information>
    <EarthQuake_Information idx="I8">
      <Force>9 ~</Force>
      <Content>수천km 지역을 완전히 파괴하는데, 약 20년에 1건 꼴로 발생</Content>
    </EarthQuake_Information>
  </EarthQuakes>
